spring.application.name=banking-portal

spring.datasource.url=${postgresql://neobank_db_4g0e_user:WV4yNuhdZ9DucBP0szd2N2GvnU5hoA2e@dpg-d6ful215pdvs73c5qubg-a/neobank_db_4g0e}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect